### ISSUE TITLE
Mismatch between paper and code

### ISSUE THREAD

**Issue by icrto** [Cardinalere/Batch-ICL#2]
Hi, thanks for sharing your very interesting work!

In Section 3.2 of the paper you mention that "At a selected layer k, we collect the fi(xq) at the last position, i.e., the result of Eq. 5.", but in the code (see e.g.  [here](https://github.com/Cardinalere/Batch-ICL/blob/7bce1a81d639aefc4bcd8f2116856809f1523fd9/Batch-ICL.py#L399)) you use the last 2 tokens.

According to the paper, shouldn't it be just the last token?

Thanks in advance.

**Comment by Cardinalere** [comment]
Thank you for your patience and for bringing this to my attention. I apologize for the delay in responding to your inquiry. This is because we believe that in a question-answering context, i.e., Q:1+1=? A:, the crucial information is encapsulated within the 'A:' (The token at the end of the sentence prompting the LLM to output the answer). However, across different tokenizers, this hint token might not necessarily be the very last one. For instance, in the Llama-2 tokenizer, 'Answer:' is tokenized into two tokens. Therefore, in my implementation, we opted to replace the last two positions to ensure the inclusion of this essential prompt.

**Comment by icrto** [comment]
I see, thank you.
