### ISSUE TITLE
Ablations

### ISSUE THREAD

**Issue by icrto** [Cardinalere/Batch-ICL#3]
Hi, thanks for sharing your very interesting work!

Did you try using more than one layer, i.e. getting the hidden states from all layers and having a per-layer aggregate that you replaced in all layers of the network? Why did you choose to only work with 1 layer at a time?

Why do you substitute the zero-shot outputs with the aggregated 1-shot hidden states? Why not adding instead of substituting?

**Comment by Cardinalere** [comment]
Thank you for your questions. I apologize for the delay in responding to your inquiry.

1. "Why did you choose to only work with 1 layer at a time?"
Considering we directly replace the hidden state, substituting multiple hidden states effectively amounts to replacing the hidden state of the final layer. For example, replacing the hidden states of both the 14th and 15th layers is essentially equivalent to replacing the hidden states of the 15th layer alone. This is because the hidden state of the 14th layer, after processing, will be replaced by the hidden state of the 15th layer.

2. "Why not adding instead of substituting?"
We believe substituting the hidden state is to enable the 0-shot to access information from the 1-shot (i.e., how to answer, answer format, etc.), which the 0-shot cannot obtain without leveraging the hidden state of the 1-shot. If we were to add them together, the proportion of 0-shot information would be too large. In practice, our implementation is based on the equation hs = (1 + a) * hs_1 - a * hs_0. It's just that we set a to 0. If you're interested, you can modify this parameter 'a' to observe its effect.

I hope my response has provided the information you needed. Feel free to let me know if you have any other questions. Wishing you all the best!

**Comment by icrto** [comment]
Thank you very much for answering my questions so clearly. I understand now.
